# 5.1 基本数据结构

## 5.1.1 元组

### 创建元组

In [1]:
t = ('上证指数', '000001', '1990-12-19', 100)
type(t)

tuple

### 定位元素

In [2]:
t[1]

'000001'

In [3]:
type(t[1])

str

### 连接元组

In [4]:
t2 = (1519, 42274.41)
t = t + t2
t

('上证指数', '000001', '1990-12-19', 100, 1519, 42274.41)

### 删除元组

In [5]:
del(t2)
t2

NameError: name 't2' is not defined

### 元素个数

In [6]:
t.count(100)

1

### 元素位置

In [7]:
t.index(100)

3

### 元组长度

In [8]:
len(t)

6

### 最大最小元素

In [9]:
max(t)

TypeError: '>' not supported between instances of 'int' and 'str'

In [10]:
t = [1, 4.5, 5] 
min(t)

1

### 转换为元组

In [11]:
li = ['上证指数', '000001', '1990-12-19', 100]   
t = tuple(li)  
t  

('上证指数', '000001', '1990-12-19', 100)

## 5.1.2 列表

### 创建列表

In [12]:
li = ['上证指数', '000001', '1990-12-19', 100]
li

['上证指数', '000001', '1990-12-19', 100]

### 定位元素

In [13]:
li[1]

'000001'

### 选取下标0-2的元素返回一个列表

In [14]:
li[0:2]          

['上证指数', '000001']

### 将[1519, 42274.41]这个列表添加在l的尾部

In [15]:
li.append([1519, 42274.41])       
li

['上证指数', '000001', '1990-12-19', 100, [1519, 42274.41]]

### 将[1519, 42274.41]列表内的元素添加在l的尾部

In [16]:
li.extend([1519, 42274.41])       
li

['上证指数', '000001', '1990-12-19', 100, [1519, 42274.41], 1519, 42274.41]

### 将'000001CNY01'这个对象插入到l中下标为6的位置

In [17]:
li.insert(6,'000001CNY01')      
li

['上证指数',
 '000001',
 '1990-12-19',
 100,
 [1519, 42274.41],
 1519,
 '000001CNY01',
 42274.41]

### 移除在l中第一次出现的元素'000001CNY01（全收益）'

In [18]:
li.remove('000001CNY01')         
li

['上证指数', '000001', '1990-12-19', 100, [1519, 42274.41], 1519, 42274.41]

### 移除在l中下标为4的元素并返回该元素

In [19]:
p = li.pop(4)        
print(li, p)

['上证指数', '000001', '1990-12-19', 100, 1519, 42274.41] [1519, 42274.41]


### 元素出现次数

In [20]:
li.count(100)

1

### 元素位置

In [21]:
li.index(100)

3

### 列表长度

In [22]:
len(li)

6

### 翻转列表

In [23]:
li.reverse()
li

[42274.41, 1519, 100, '1990-12-19', '000001', '上证指数']

### 列表内元素排序

In [24]:
li.sort()
li

TypeError: '<' not supported between instances of 'str' and 'int'

### 清除列表内所有元素

In [25]:
li.clear()
li

[]

## 5.1.3 字典

### 创建字典

In [26]:
d = {'name':'上证指数',
     'code':'000001',
     'date':'1990-12-19',
     'point':100}
type(d)

dict

### 根据键值查找

In [27]:
d['code']

'000001'

### 所有键值

In [28]:
d.keys()

dict_keys(['name', 'code', 'date', 'point'])

### 所有对应值

In [29]:
d.values()

dict_values(['上证指数', '000001', '1990-12-19', 100])

### 输出键值对

In [30]:
for item in d.items():
    print(item)

('name', '上证指数')
('code', '000001')
('date', '1990-12-19')
('point', 100)


### 更新字典

In [31]:
d['number of stocks']=1518
d

{'name': '上证指数',
 'code': '000001',
 'date': '1990-12-19',
 'point': 100,
 'number of stocks': 1518}

In [32]:
d['number of stocks']=1519
d

{'name': '上证指数',
 'code': '000001',
 'date': '1990-12-19',
 'point': 100,
 'number of stocks': 1519}

### 使'number of stocks'对应的值加一

In [33]:
d['number of stocks']+=1
d['number of stocks']

1520

### 删除键值为'number of stocks'的元素 

In [34]:
del(d['number of stocks'])
d

{'name': '上证指数', 'code': '000001', 'date': '1990-12-19', 'point': 100}

### 用新内容进行替代 

In [35]:
d.update({'name':'B股指数', 'code': '000003', 'date': '1992-02-21'}) 
d

{'name': 'B股指数', 'code': '000003', 'date': '1992-02-21', 'point': 100}

### 完整复制

In [36]:
dc = d.copy()
dc

{'name': 'B股指数', 'code': '000003', 'date': '1992-02-21', 'point': 100}

### 删除字典

In [37]:
del(d)
d

NameError: name 'd' is not defined

## 5.1.4 集合

### 创建集合

In [38]:
s1 = set(['a','b','c','ab','ac','a'])
s1

{'a', 'ab', 'ac', 'b', 'c'}

In [39]:
s2 = set(['ab','ac','bc','c'])

### 添加元素

In [40]:
s1.add('d')
s1

{'a', 'ab', 'ac', 'b', 'c', 'd'}

### 更新元素

In [41]:
s1.update('d','e')
s1

{'a', 'ab', 'ac', 'b', 'c', 'd', 'e'}

### 移除元素

In [42]:
s1.remove('d')
s1

{'a', 'ab', 'ac', 'b', 'c', 'e'}

In [43]:
s1.discard('e')
s1

{'a', 'ab', 'ac', 'b', 'c'}

### 取并集 s1 | s2

In [44]:
s1.union(s2)

{'a', 'ab', 'ac', 'b', 'bc', 'c'}

### 取交集 s1 & s2

In [45]:
s1.intersection(s2)

{'ab', 'ac', 'c'}

### 在s1中但不在s2中  s1 - s2

In [46]:
s1.difference(s2)

{'a', 'b'}

### 只在二者之一中  s1 ^ s2

In [47]:
s1.symmetric_difference(s2)

{'a', 'b', 'bc'}

### 实现对列表li的去重

In [48]:
li = [1, 2, 3, 3, 4, 4, 5]
s = set(li)
s

{1, 2, 3, 4, 5}

# 5.2 numpy的使用

## 5.2.2 numpy常规数组

### 创建一维数组

In [49]:
import numpy as np 
a = np.array([1,2,3])    
a

array([1, 2, 3])

### 创建二维数组

In [50]:
b = np.array([[1, 2],  [3, 4]])    
b

array([[1, 2],
       [3, 4]])

### 创建特殊数组

In [51]:
a = np.zeros((2,3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [52]:
a = np.ones((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

### 创建等差等比数列

In [53]:
a = np.arange(2,5,1)
a

array([2, 3, 4])

In [54]:
a = np.linspace(1,5,5)
a

array([1., 2., 3., 4., 5.])

In [55]:
a = np.logspace(0,3,4,base=5)
a

array([  1.,   5.,  25., 125.])

### 创建数组

In [56]:
import numpy as np 
a = np.array(['上证指数','000001','1990-12-19',100])    
a

array(['上证指数', '000001', '1990-12-19', '100'], dtype='<U10')

### 查找元素

In [57]:
a[1]

'000001'

In [58]:
b[1]

array([3, 4])

In [59]:
b[1][1]

4

### 截取

In [60]:
b[1:]

array([[3, 4]])

### 更新元素

In [61]:
b[1][0] = 5
b

array([[1, 2],
       [5, 4]])

### 合并数组

In [62]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [63]:
np.hstack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

### 数组运算

In [64]:
a = np.array([[1],[2]]) 
b = ([[10,20,30]]) 
a+b 

array([[11, 21, 31],
       [12, 22, 32]])

### 元素查找

In [65]:
a = a[0]
a

array([1])

### 删除元素

In [66]:
a = np.array([[1,2,3],[3,4,5],[5,6,7]]) 
np.delete(a,1,axis = 0) 

array([[1, 2, 3],
       [5, 6, 7]])

In [67]:
np.delete(a,(1,2),axis = 1)

array([[1],
       [3],
       [5]])

### 数组维度

In [68]:
b = np.array([[1, 2],  [3, 4]])    
b.shape

(2, 2)

### 数组元素类型

In [69]:
b.dtype

dtype('int64')

### 数组大小

In [70]:
b.size

4

### 数组元素大小

In [71]:
b.itemsize

8

### 求和

In [72]:
b.sum()

10

### 按列求和

In [73]:
b.sum(axis=0)

array([4, 6])

### 按行求和

In [74]:
b.sum(axis=1)

array([3, 7])

### 求平均值

In [75]:
b.mean()

2.5

### 求标准差

In [76]:
b.std()

1.118033988749895

### 求累计和，即自己和之前所有的数字之和，常用于统计

In [77]:
b.cumsum()

array([ 1,  3,  6, 10])

## 5.2.3 numpy结构化数组

### 创建结构化数组

In [78]:
import numpy as np 
a = np.array([('上证指数', '000001', '1990-12-19', 100), ('B股指数', '000003', '1992-02-21', 100)],
              dtype=[('name', 'U10'), ('code', 'U10'), ('date', 'datetime64[D]'), ('point', 'i4')])
a

array([('上证指数', '000001', '1990-12-19', 100),
       ('B股指数', '000003', '1992-02-21', 100)],
      dtype=[('name', '<U10'), ('code', '<U10'), ('date', '<M8[D]'), ('point', '<i4')])

### 查找元素

In [79]:
a['name']

array(['上证指数', 'B股指数'], dtype='<U10')

### 查找code为000001的对象的名称

In [80]:
a[a['code']=='000001']['name']

array(['上证指数'], dtype='<U10')

## 5.2.4 numpy向量化操作

### 创建数组

In [129]:
import numpy as np 
a = np.random.standard_normal((4,3))
a

array([[ 0.0389046 ,  1.39797971,  1.3323659 ],
       [-1.17183676, -0.0592499 ,  0.54157041],
       [-0.3332645 , -0.66559073,  0.38837014],
       [-0.27835082,  1.45261006, -0.11257387]])

In [130]:
b = np.random.standard_normal((4,3))
b

array([[ 0.17669435,  0.97816475, -0.71704226],
       [ 0.65864705,  0.32893351,  0.07342595],
       [-0.77339999, -0.06944655, -0.26590534],
       [-0.76827422,  0.9727153 ,  0.06096575]])

### 数组间加法运算

In [131]:
a+b

array([[ 0.21559895,  2.37614447,  0.61532364],
       [-0.51318971,  0.26968361,  0.61499636],
       [-1.10666448, -0.73503728,  0.12246479],
       [-1.04662504,  2.42532536, -0.05160812]])

### 对内部所有元素*2并+1

In [132]:
a*2 +1

array([[ 1.07780921,  3.79595943,  3.66473179],
       [-1.34367352,  0.88150019,  2.08314082],
       [ 0.333471  , -0.33118146,  1.77674027],
       [ 0.44329836,  3.90522012,  0.77485226]])

### 转置

In [86]:
b.transpose()

array([[ 0.9457445 ,  0.21638635, -0.44740843, -0.33955471],
       [-0.77231435, -0.7634424 ,  0.16265641,  0.5783542 ],
       [-0.61680267, -1.39399311, -0.93398591, -1.12769424]])

### 矩阵乘，要求a的列数与b的行数相同

In [87]:
np.dot(a,b.transpose())

array([[-2.52677632, -2.09863848,  0.20095576,  0.50895189],
       [-1.24113144, -0.56266164,  0.28236591,  0.06481535],
       [-0.05212119, -0.94367683, -0.75626706, -0.65634167],
       [ 0.61892729,  0.24983309,  0.40009584,  1.36901757]])

### 重组，要求重组后的数组内元素数量与重组前相同

In [88]:
a.reshape(2,6)

array([[-1.20123371,  1.32824618,  0.59158717, -1.21147188, -0.08649032,
         0.26294681],
       [ 0.60981274,  0.35191473,  0.57888763,  1.40617766,  1.5807765 ,
        -0.82668073]])

# 5.3 pandas的使用

## 5.3.2 pandas-Series

### 创建Series

In [89]:
import pandas as pd
ser = pd.Series([1,2,3,4],index =['a','b','c','d'])
ser

a    1
b    2
c    3
d    4
dtype: int64

In [90]:
ser2 = pd.Series(['上证指数','000001','1990-12-19',100],index =['name','code','date','point'])
ser2

name           上证指数
code         000001
date     1990-12-19
point           100
dtype: object

### 查找、定位元素

In [91]:
ser.loc['b']

2

In [92]:
ser.iloc[1]

2

In [93]:
ser[['a','c']]

a    1
c    3
dtype: int64

In [94]:
ser.loc['b':'d']

b    2
c    3
d    4
dtype: int64

### 更新元素

In [95]:
ser['b'] = 10
ser

a     1
b    10
c     3
d     4
dtype: int64

### 连接Series

In [96]:
ser3 = pd.Series([11],index =['f'])
ser = ser.append(ser3)
ser

a     1
b    10
c     3
d     4
f    11
dtype: int64

### 删除Series中元素

In [97]:
ser.drop('b')

a     1
c     3
d     4
f    11
dtype: int64

## 5.3.3 pandas-DataFrame

### 创建DataFrame

In [98]:
import pandas as pd
df = pd.DataFrame([['上证指数','000001','1990-12-19',100],['B股指数','000003','1992-02-21',100]],
                    index =['row1','row2'],
                    columns = ['name','code','date','point'])
df

name    code        date  point
row1  上证指数  000001  1990-12-19    100
row2  B股指数  000003  1992-02-21    100

### 通过字典创建DataFrame

In [99]:
d = {'name':['上证指数','B股指数'],
     'code':['000001','000003'],
     'date':['1990-12-19','1992-02-21'],
     'point':[100,100]}
pd.DataFrame(d)

name    code        date  point
0  上证指数  000001  1990-12-19    100
1  B股指数  000003  1992-02-21    100

### 定位元素

In [100]:
df.loc['row1','name']

'上证指数'

In [101]:
type(df.loc['row2'])

pandas.core.series.Series

In [144]:
df['name']

row1    A股指数
row2    B股指数
Name: name, dtype: object

In [ ]:
type(df['name'])

In [103]:
df[['name','code']]

name    code
row1  上证指数  000001
row2  B股指数  000003

In [104]:
df[['name','code']].loc['row2':]

name    code
row2  B股指数  000003

In [105]:
df.loc['row1','name'] = 'A股指数'
df

name    code        date  point
row1  A股指数  000001  1990-12-19    100
row2  B股指数  000003  1992-02-21    100

In [106]:
df.loc['row1'] = ['A股指数','000002','1990-12-19',100]
df

name    code        date  point
row1  A股指数  000002  1990-12-19    100
row2  B股指数  000003  1992-02-21    100

### 更新元素

In [107]:
df['point']=101
df

name    code        date  point
row1  A股指数  000002  1990-12-19    101
row2  B股指数  000003  1992-02-21    101

In [108]:
df['point']=[0,1]
df

name    code        date  point
row1  A股指数  000002  1990-12-19      0
row2  B股指数  000003  1992-02-21      1

### 元素判断

In [109]:
df['point']>0

row1    False
row2     True
Name: point, dtype: bool

### 连接DataFrame

In [110]:
df1 = pd.DataFrame([['上证380','000009','2003-12-31',1000]],
                    index =['row3'],
                    columns = ['name','code','date','point'])
df.append(df1)

name    code        date  point
row1   A股指数  000002  1990-12-19      0
row2   B股指数  000003  1992-02-21      1
row3  上证380  000009  2003-12-31   1000

In [111]:
df1 = pd.DataFrame([['上证380','000009','2003-12-31',1000]],
                    index =['row3'])
df.append(df1)

/usr/local/install_package/anaconda3/lib/python3.7/site-packages/pandas/core/indexes/api.py:107: RuntimeWarning: '<' not supported between instances of 'str' and 'int', sort order is undefined for incomparable objects
  result = result.union(other)


name    code        date  point      0       1           2       3
row1  A股指数  000002  1990-12-19    0.0    NaN     NaN         NaN     NaN
row2  B股指数  000003  1992-02-21    1.0    NaN     NaN         NaN     NaN
row3   NaN     NaN         NaN    NaN  上证380  000009  2003-12-31  1000.0

### 添加新列

In [112]:
df['amount']=[1475,44]
df

name    code        date  point  amount
row1  A股指数  000002  1990-12-19      0    1475
row2  B股指数  000003  1992-02-21      1      44

### 删除列

In [113]:
del(df['point'])  
df

name    code        date  amount
row1  A股指数  000002  1990-12-19    1475
row2  B股指数  000003  1992-02-21      44

### DataFrame元素相加

In [114]:
df1 = pd.DataFrame([['上证指数','000001','1990-12-19',100],['B股指数','000003','1992-02-21',100]],
                    index =['row1','row2'],
                    columns = ['name','code','date','amount'])
df1+df

name          code                  date  amount
row1  上证指数A股指数  000001000002  1990-12-191990-12-19    1575
row2  B股指数B股指数  000003000003  1992-02-211992-02-21     144

### DataFrame重排列

In [115]:
df.reindex(['row2','row1','row3'])

name    code        date  amount
row2  B股指数  000003  1992-02-21    44.0
row1  A股指数  000002  1990-12-19  1475.0
row3   NaN     NaN         NaN     NaN

### 重定义索引

In [116]:
df.reset_index()

index  name    code        date  amount
0  row1  A股指数  000002  1990-12-19    1475
1  row2  B股指数  000003  1992-02-21      44

In [117]:
df.set_index('name')

code        date  amount
name                            
A股指数  000002  1990-12-19    1475
B股指数  000003  1992-02-21      44

### 查看信息

In [118]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2 entries, row1 to row2
Data columns (total 4 columns):
name      2 non-null object
code      2 non-null object
date      2 non-null object
amount    2 non-null int64
dtypes: int64(1), object(3)
memory usage: 160.0+ bytes


### 统计函数应用

In [119]:
import numpy as np
np.sqrt(df['amount'])

row1    38.405729
row2     6.633250
Name: amount, dtype: float64

In [120]:
df1 = pd.DataFrame([[5.456,6,7.5635,-0.241],[1.783,6.2,8,5.2785]])
df1.sum(axis=0)

0     7.2390
1    12.2000
2    15.5635
3     5.0375
dtype: float64

In [121]:
df1.describe()

0         1         2         3
count  2.000000  2.000000  2.000000  2.000000
mean   3.619500  6.100000  7.781750  2.518750
std    2.597203  0.141421  0.308652  3.902876
min    1.783000  6.000000  7.563500 -0.241000
25%    2.701250  6.050000  7.672625  1.138875
50%    3.619500  6.100000  7.781750  2.518750
75%    4.537750  6.150000  7.890875  3.898625
max    5.456000  6.200000  8.000000  5.278500

### 函数映射

In [122]:
f = lambda x:x.max() - x.min()
df1.apply(f)

0    3.6730
1    0.2000
2    0.4365
3    5.5195
dtype: float64

In [123]:
format = lambda x:'%.2f'%x
df1.applymap(format)

0     1     2      3
0  5.46  6.00  7.56  -0.24
1  1.78  6.20  8.00   5.28

### 元素排列

In [124]:
df1.sort_values(by=0,axis=0,ascending=True)

0    1       2       3
1  1.783  6.2  8.0000  5.2785
0  5.456  6.0  7.5635 -0.2410

### 处理缺失值

In [125]:
df.isnull().sum()

name      0
code      0
date      0
amount    0
dtype: int64

In [126]:
df2 = pd.DataFrame([[1,2,3],[1,2,np.nan],[np.nan,np.nan,np.nan]])
df2.dropna(how='all',axis=0)

0    1    2
0  1.0  2.0  3.0
1  1.0  2.0  NaN

In [127]:
df2.fillna(0)

0    1    2
0  1.0  2.0  3.0
1  1.0  2.0  0.0
2  0.0  0.0  0.0

In [128]:
df2.fillna(method='ffill')

0    1    2
0  1.0  2.0  3.0
1  1.0  2.0  3.0
2  1.0  2.0  3.0